# Generated by Django 5.2.15 on 2026-06-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('coin', models.CharField(choices=[('USDT', 'USDT'), ('BTC', 'BTC'), ('ETH', 'ETH')], max_length=8)),
                ('note', models.TextField(blank=True, default='')),
                ('requester_user_id', models.CharField(db_index=True, max_length=32)),
                ('requester_username', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requester_user_id', 'created_at'], name='links_payme_request_69eabb_idx')],
            },
        ),
    ]
